version: "2"
services:
  siglus-ui:
    image: siglusdevops/dev-ui:9.0.5-3
    dns:
      - 8.8.8.8
    ports:
      - "9000:9000"
      - "9876:9876"
    working_dir: /app
    volumes:
      - '.:/app'
    env_file: .env
    volumes_from:
      - auth-ui
      - referencedata-ui
      - requisition-ui
      - stockmanagement-ui
      - ui-components
      - ui-layout
      - fulfillment-ui
    depends_on:
      - auth-ui
      - referencedata-ui
      - requisition-ui
      - stockmanagement-ui
      - ui-components
      - ui-layout
      - fulfillment-ui
  auth-ui:
    image: openlmis/auth-ui:6.2.3
    volumes:
      - '/openlmis-auth-ui'
  referencedata-ui:
    image: openlmis/referencedata-ui:5.6.2
    volumes:
      - '/openlmis-referencedata-ui'
  requisition-ui:
    image: openlmis/requisition-ui:7.0.2
    volumes:
      - '/openlmis-requisition-ui'
  stockmanagement-ui:
    image: openlmis/stockmanagement-ui:2.0.6
    volumes:
      - '/openlmis-stockmanagement-ui'
  ui-components:
    image: openlmis/ui-components:7.2.2
    volumes:
      - '/openlmis-ui-components'
  ui-layout:
    image: openlmis/ui-layout:5.1.6
    volumes:
      - '/openlmis-ui-layout'
  fulfillment-ui:
    image: openlmis/fulfillment-ui:6.0.6
    volumes:
      - '/openlmis-fulfillment-ui'
  image:
    build: .
    image: siglusdevops/siglus-ui
